CREATE TABLE USUARIOS (
  IDUSUARIO TEXT PRIMARY KEY,
  NOMBRES TEXT NOT NULL,
  CONTRASENA TEXT NOT NULL,
  TELEFONO TEXT NOT NULL,
  ESTADO TEXT NOT NULL,
  EMAIL TEXT UNIQUE,
  IMAGENPERFIL BYTEA,
  PAIS TEXT NOT NULL,
  CIUDAD TEXT NOT NULL,
  FECHANACIMIENTO DATE
);

CREATE TABLE GRUPOSCOLABORADORES (
  IDGRUPO TEXT PRIMARY KEY,
  NOMBREGRUPO TEXT,
  DESCRIPCION TEXT,
  IMAGEN BYTEA,
  FECHACREACION DATE
);

CREATE TABLE USUARIOSGRUPOS (
  IDUSUARIO TEXT,
  IDGRUPO TEXT,
  PRIMARY KEY (IDUSUARIO, IDGRUPO),
  CONSTRAINT FK_USUARIOSGRUPOS_USUARIOS FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO) ON DELETE CASCADE,
  CONSTRAINT FK_USUARIOSGRUPOS_GRUPOSCOLABORADORES FOREIGN KEY (IDGRUPO) REFERENCES GRUPOSCOLABORADORES(IDGRUPO) ON DELETE CASCADE
);

CREATE TABLE ROL (
  IDROL TEXT PRIMARY KEY,
  PERMISO TEXT,
  DESCRIPCION TEXT NOT NULL
);

CREATE TABLE USUARIOROL (
  IDUSUARIO TEXT,
  IDROL TEXT,
  PRIMARY KEY (IDUSUARIO, IDROL),
  CONSTRAINT FK_USUARIOROL_USUARIOS FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO) ON DELETE CASCADE,
  CONSTRAINT FK_USUARIOROL_ROL FOREIGN KEY (IDROL) REFERENCES ROL(IDROL) ON DELETE CASCADE
);

CREATE TABLE PROYECTOS (
  IDPROYECTO TEXT PRIMARY KEY,
  NOMBRE TEXT NOT NULL,
  IDEA TEXT NOT NULL,
  DESCRIPCION TEXT,
  FECHALIMITE DATE,
  PRESENTACION BYTEA NOT NULL,
  PRESUPUESTO NUMERIC(10, 2),
  RECOMPENSA TEXT,
  METAALCANZADA NUMERIC DEFAULT 0,
  ESTADO TEXT,
  IDGRUPO TEXT,
  CONSTRAINT FK_PROYECTOS_GRUPOS FOREIGN KEY (IDGRUPO) REFERENCES GRUPOSCOLABORADORES(IDGRUPO) ON DELETE SET NULL
);

CREATE TABLE PROYECTOSCATEGORIAS (
  IDPROYECTO TEXT,
  IDCATEGORIA TEXT,
  PRIMARY KEY (IDPROYECTO, IDCATEGORIA),
  CONSTRAINT FK_PROYECTOSCATEGORIAS_PROYECTOS FOREIGN KEY (IDPROYECTO) REFERENCES PROYECTOS(IDPROYECTO) ON DELETE CASCADE,
  CONSTRAINT FK_PROYECTOSCATEGORIAS_CATEGORIAS FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIAS(IDCATEGORIA) ON DELETE CASCADE
);

CREATE TABLE CATEGORIAS (
  IDCATEGORIA TEXT PRIMARY KEY,
  IDSUBCATEGORIA TEXT,
  NOMBRECATEGORIA TEXT NOT NULL,
  CONSTRAINT FK_CATEGORIAS_SUBCATEGORIAS FOREIGN KEY (IDSUBCATEGORIA) REFERENCES SUBCATEGORIAS(IDSUBCATEGORIA) ON DELETE SET NULL
);

CREATE TABLE SUBCATEGORIAS (
  IDSUBCATEGORIA TEXT PRIMARY KEY,
  NOMBRESUBCATEGORIA TEXT
);

CREATE TABLE ESTADOS (
  IDESTADO TEXT PRIMARY KEY,
  NOMBREESTADO TEXT
);

CREATE TABLE COMENTARIOS (
  IDCOMENTARIO TEXT PRIMARY KEY,
  COMENTARIO TEXT,
  FECHACOMENTARIO DATE,
  IDUSUARIO TEXT,
  IDPROYECTO TEXT,
  CONSTRAINT FK_COMENTARIOS_USUARIOS FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO) ON DELETE CASCADE,
  CONSTRAINT FK_COMENTARIOS_PROYECTOS FOREIGN KEY (IDPROYECTO) REFERENCES PROYECTOS(IDPROYECTO) ON DELETE CASCADE
);

CREATE TABLE IMAGENESPROYECTO (
  IDIMAGENES TEXT PRIMARY KEY,
  ARCHIVO TEXT NOT NULL
);

CREATE TABLE DONACION (
  IDDONACION TEXT PRIMARY KEY,
  MONTO NUMERIC NOT NULL,
  FECHADONACION DATE,
  IDUSUARIO TEXT,
  IDPROYECTO TEXT,
  CONSTRAINT FK_DONACION_USUARIOS FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO) ON DELETE CASCADE,
  CONSTRAINT FK_DONACION_PROYECTOS FOREIGN KEY (IDPROYECTO) REFERENCES PROYECTOS(IDPROYECTO) ON DELETE CASCADE
);

CREATE TABLE PROYECTOS_DONACION (
  IDPROYECTO TEXT,
  IDDONACION TEXT,
  PRIMARY KEY (IDPROYECTO, IDDONACION),
  CONSTRAINT FK_PROYECTOS_DONACION_PROYECTOS FOREIGN KEY (IDPROYECTO) REFERENCES PROYECTOS(IDPROYECTO) ON DELETE CASCADE,
  CONSTRAINT FK_PROYECTOS_DONACION_DONACION FOREIGN KEY (IDDONACION) REFERENCES DONACION(IDDONACION) ON DELETE CASCADE
);

CREATE TABLE METODOPAGO (
  IDMETODOPAGO TEXT PRIMARY KEY,
  MONTO NUMERIC NOT NULL,
  FECHA DATE,
  IDPAYPAL TEXT,
  IDCUENTABANCARIA TEXT,
  IDTARJETA TEXT
);

CREATE TABLE PAYPAL (
  IDPAYPAL TEXT PRIMARY KEY,
  EMAIL TEXT
);

CREATE TABLE TARJETA (
  IDTARJETA TEXT PRIMARY KEY,
  BANCO TEXT,
  TELEFONO TEXT,
  DVD TEXT,
  FECHAVENCIMIENTO DATE
);

CREATE TABLE IDCUENTABANCARIA (
  IDCUENTABANCARIA TEXT PRIMARY KEY,
  BANCO TEXT,
  TIPO TEXT,
  FECHAVENCIMIENTO DATE
);

CREATE TABLE REDES (
  IDREDES TEXT PRIMARY KEY,
  NOMBRE TEXT NOT NULL,
  URL TEXT NOT NULL
);

CREATE TABLE RECOMPENSA (
  IDRECOMPENSA TEXT PRIMARY KEY,
  FECHAADQUISICION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  AGRADECIMIENTO TEXT
);
