-- Eliminar las restricciones de clave foránea
ALTER TABLE USUARIOSGRUPOS DROP CONSTRAINT FK_USUARIOSGRUPOS_USUARIOS;
ALTER TABLE USUARIOSGRUPOS DROP CONSTRAINT FK_USUARIOSGRUPOS_GRUPOSCOLABORADORES;
ALTER TABLE USUARIOROL DROP CONSTRAINT FK_USUARIOROL_USUARIOS;
ALTER TABLE USUARIOROL DROP CONSTRAINT FK_USUARIOROL_ROL;
ALTER TABLE PROYECTOSCATEGORIAS DROP CONSTRAINT FK_PROYECTOSCATEGORIAS_PROYECTOS;
ALTER TABLE PROYECTOSCATEGORIAS DROP CONSTRAINT FK_PROYECTOSCATEGORIAS_CATEGORIAS;
ALTER TABLE CATEGORIAS DROP CONSTRAINT FK_CATEGORIAS_SUBCATEGORIAS;
ALTER TABLE COMENTARIOS DROP CONSTRAINT FK_COMENTARIOS_USUARIOS;
ALTER TABLE COMENTARIOS DROP CONSTRAINT FK_COMENTARIOS_PROYECTOS;
ALTER TABLE DONACION DROP CONSTRAINT FK_DONACION_USUARIOS;
ALTER TABLE DONACION DROP CONSTRAINT FK_DONACION_PROYECTOS;
ALTER TABLE METODOPAGO DROP CONSTRAINT FK_METODOPAGO_PAYPAL;
ALTER TABLE METODOPAGO DROP CONSTRAINT FK_METODOPAGO_IDCUENTABANCARIA;
ALTER TABLE METODOPAGO DROP CONSTRAINT FK_METODOPAGO_TARJETA;

-- Eliminar las tablas
DROP TABLE USUARIOS;
DROP TABLE GRUPOSCOLABORADORES;
DROP TABLE USUARIOSGRUPOS;
DROP TABLE ROL;
DROP TABLE USUARIOROL;
DROP TABLE PROYECTOS;
DROP TABLE PROYECTOSCATEGORIAS;
DROP TABLE CATEGORIAS;
DROP TABLE SUBCATEGORIAS;
DROP TABLE ESTADOS;
DROP TABLE COMENTARIOS;
DROP TABLE IMAGENESPROYECTO;
DROP TABLE DONACION;
DROP TABLE PROYECTOS_DONACION;
DROP TABLE METODOPAGO;
DROP TABLE PAYPAL;
DROP TABLE TARJETA;
DROP TABLE IDCUENTABANCARIA;
DROP TABLE REDES;
DROP TABLE RECOMPENSA;