-- Eliminar las restricciones de clave foránea
ALTER TABLE
    USUARIOSGRUPOS DROP CONSTRAINT IF EXISTS FK_USUARIOSGRUPOS_USUARIOS;

ALTER TABLE
    USUARIOSGRUPOS DROP CONSTRAINT IF EXISTS FK_USUARIOSGRUPOS_GRUPOSCOLABORADORES;

ALTER TABLE
    USUARIOROL DROP CONSTRAINT IF EXISTS FK_USUARIOROL_USUARIOS;

ALTER TABLE
    USUARIOROL DROP CONSTRAINT IF EXISTS FK_USUARIOROL_ROL;

ALTER TABLE
    PROYECTOSCATEGORIAS DROP CONSTRAINT IF EXISTS FK_PROYECTOSCATEGORIAS_PROYECTOS;

ALTER TABLE
    PROYECTOSCATEGORIAS DROP CONSTRAINT IF EXISTS FK_PROYECTOSCATEGORIAS_CATEGORIAS;

ALTER TABLE
    CATEGORIAS DROP CONSTRAINT IF EXISTS FK_CATEGORIAS_SUBCATEGORIAS;

ALTER TABLE
    COMENTARIOS DROP CONSTRAINT IF EXISTS FK_COMENTARIOS_USUARIOS;

ALTER TABLE
    COMENTARIOS DROP CONSTRAINT IF EXISTS FK_COMENTARIOS_PROYECTOS;

ALTER TABLE
    DONACION DROP CONSTRAINT IF EXISTS FK_DONACION_USUARIOS;

ALTER TABLE
    DONACION DROP CONSTRAINT IF EXISTS FK_DONACION_PROYECTOS;

ALTER TABLE
    METODOPAGO DROP CONSTRAINT IF EXISTS FK_METODOPAGO_PAYPAL;

ALTER TABLE
    METODOPAGO DROP CONSTRAINT IF EXISTS FK_METODOPAGO_IDCUENTABANCARIA;

ALTER TABLE
    METODOPAGO DROP CONSTRAINT IF EXISTS FK_METODOPAGO_TARJETA;

-- Eliminar las tablas
DROP TABLE IF EXISTS USUARIOS;

DROP TABLE IF EXISTS GRUPOSCOLABORADORES;

DROP TABLE IF EXISTS USUARIOSGRUPOS;

DROP TABLE IF EXISTS ROL;

DROP TABLE IF EXISTS USUARIOROL;

DROP TABLE IF EXISTS PROYECTOS;

DROP TABLE IF EXISTS PROYECTOSCATEGORIAS;

DROP TABLE IF EXISTS CATEGORIAS;

DROP TABLE IF EXISTS SUBCATEGORIAS;

DROP TABLE IF EXISTS ESTADOS;

DROP TABLE IF EXISTS COMENTARIOS;

DROP TABLE IF EXISTS IMAGENESPROYECTO;

DROP TABLE IF EXISTS DONACION;

DROP TABLE IF EXISTS PROYECTOS_DONACION;

DROP TABLE IF EXISTS METODOPAGO;

DROP TABLE IF EXISTS PAYPAL;

DROP TABLE IF EXISTS TARJETA;

DROP TABLE IF EXISTS IDCUENTABANCARIA;

DROP TABLE IF EXISTS REDES;

DROP TABLE IF EXISTS RECOMPENSA;